require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'PreventScriptsRPM' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RCTAppleHealthKit', :path => '../node_modules/rn-apple-healthkit'
  pod 'Beacon'
  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications/Permission-Notifications.podspec"
  target 'PreventScriptsRPMTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  # pre_install do |installer|
  #   installer.pod_targets.each do |pod|
  #     if pod.name.eql?('RNScreens')
  #       def pod.build_type
  #         Pod::BuildType.static_library
  #       end
  #     end
  #    end
  #  end
  post_install do |installer|
    react_native_post_install(installer)
  end
end