# Generated by Django 2.2.24 on 2021-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='last_login_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
