# Generated by Django 2.2.24 on 2021-08-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210803_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='dob',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
