# Generated by Django 2.2.24 on 2021-08-10 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210803_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
