# Generated by Django 2.2.24 on 2021-09-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210824_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='height',
            name='height',
            field=models.CharField(max_length=8),
        ),
    ]
